global:
  scrape_interval: 5s

rule_files:
  - "/etc/rules.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alert_manager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
