version: "3.7"
services:
  prometheus:
    build:
      context: .
      dockerfile: prometheus.Dockerfile
    image: compose_prometheus
    networks:
      - promnet
    ports: 
      - 9090:9090
  node_exporter:
    image: prom/node-exporter
    networks: 
      - promnet
networks:
  promnet: